// Generated by rstantools.  Do not edit by hand.

/*
    YEAR: 2020
    COPYRIGHT HOLDER: Asael Alonzo Matamoros

    varstan is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    varstan is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with varstan.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.19.1
#include <stan/model/model_header.hpp>
namespace model_varma_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_varma");
    reader.add_event(107, 105, "end", "model_varma");
    return reader;
}
#include <stan_meta_header.hpp>
class model_varma : public prob_grad {
private:
        int n;
        int d;
        int p;
        int q;
        matrix_d y;
        vector_d prior_mu0;
        vector_d prior_sigma0;
        vector_d prior_lkj;
        matrix_d prior_ar;
        matrix_d prior_ma;
public:
    model_varma(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_varma(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_varma_namespace::model_varma";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 2;
            context__.validate_dims("data initialization", "n", "int", context__.to_vec());
            n = int(0);
            vals_i__ = context__.vals_i("n");
            pos__ = 0;
            n = vals_i__[pos__++];
            check_greater_or_equal(function__, "n", n, 0);
            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "d", "int", context__.to_vec());
            d = int(0);
            vals_i__ = context__.vals_i("d");
            pos__ = 0;
            d = vals_i__[pos__++];
            check_greater_or_equal(function__, "d", d, 1);
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "p", "int", context__.to_vec());
            p = int(0);
            vals_i__ = context__.vals_i("p");
            pos__ = 0;
            p = vals_i__[pos__++];
            check_greater_or_equal(function__, "p", p, 0);
            current_statement_begin__ = 5;
            context__.validate_dims("data initialization", "q", "int", context__.to_vec());
            q = int(0);
            vals_i__ = context__.vals_i("q");
            pos__ = 0;
            q = vals_i__[pos__++];
            check_greater_or_equal(function__, "q", q, 0);
            current_statement_begin__ = 6;
            validate_non_negative_index("y", "n", n);
            validate_non_negative_index("y", "d", d);
            context__.validate_dims("data initialization", "y", "matrix_d", context__.to_vec(n,d));
            y = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(n, d);
            vals_r__ = context__.vals_r("y");
            pos__ = 0;
            size_t y_j_2_max__ = d;
            size_t y_j_1_max__ = n;
            for (size_t j_2__ = 0; j_2__ < y_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < y_j_1_max__; ++j_1__) {
                    y(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 7;
            validate_non_negative_index("prior_mu0", "4", 4);
            context__.validate_dims("data initialization", "prior_mu0", "vector_d", context__.to_vec(4));
            prior_mu0 = Eigen::Matrix<double, Eigen::Dynamic, 1>(4);
            vals_r__ = context__.vals_r("prior_mu0");
            pos__ = 0;
            size_t prior_mu0_j_1_max__ = 4;
            for (size_t j_1__ = 0; j_1__ < prior_mu0_j_1_max__; ++j_1__) {
                prior_mu0(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 8;
            validate_non_negative_index("prior_sigma0", "4", 4);
            context__.validate_dims("data initialization", "prior_sigma0", "vector_d", context__.to_vec(4));
            prior_sigma0 = Eigen::Matrix<double, Eigen::Dynamic, 1>(4);
            vals_r__ = context__.vals_r("prior_sigma0");
            pos__ = 0;
            size_t prior_sigma0_j_1_max__ = 4;
            for (size_t j_1__ = 0; j_1__ < prior_sigma0_j_1_max__; ++j_1__) {
                prior_sigma0(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 9;
            validate_non_negative_index("prior_lkj", "4", 4);
            context__.validate_dims("data initialization", "prior_lkj", "vector_d", context__.to_vec(4));
            prior_lkj = Eigen::Matrix<double, Eigen::Dynamic, 1>(4);
            vals_r__ = context__.vals_r("prior_lkj");
            pos__ = 0;
            size_t prior_lkj_j_1_max__ = 4;
            for (size_t j_1__ = 0; j_1__ < prior_lkj_j_1_max__; ++j_1__) {
                prior_lkj(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 10;
            validate_non_negative_index("prior_ar", "p", p);
            validate_non_negative_index("prior_ar", "4", 4);
            context__.validate_dims("data initialization", "prior_ar", "matrix_d", context__.to_vec(p,4));
            prior_ar = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(p, 4);
            vals_r__ = context__.vals_r("prior_ar");
            pos__ = 0;
            size_t prior_ar_j_2_max__ = 4;
            size_t prior_ar_j_1_max__ = p;
            for (size_t j_2__ = 0; j_2__ < prior_ar_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < prior_ar_j_1_max__; ++j_1__) {
                    prior_ar(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 11;
            validate_non_negative_index("prior_ma", "q", q);
            validate_non_negative_index("prior_ma", "4", 4);
            context__.validate_dims("data initialization", "prior_ma", "matrix_d", context__.to_vec(q,4));
            prior_ma = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(q, 4);
            vals_r__ = context__.vals_r("prior_ma");
            pos__ = 0;
            size_t prior_ma_j_2_max__ = 4;
            size_t prior_ma_j_1_max__ = q;
            for (size_t j_2__ = 0; j_2__ < prior_ma_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < prior_ma_j_1_max__; ++j_1__) {
                    prior_ma(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 15;
            validate_non_negative_index("mu0", "d", d);
            num_params_r__ += d;
            current_statement_begin__ = 16;
            validate_non_negative_index("phi", "d", d);
            validate_non_negative_index("phi", "d", d);
            validate_non_negative_index("phi", "p", p);
            num_params_r__ += ((d * d) * p);
            current_statement_begin__ = 17;
            validate_non_negative_index("theta", "d", d);
            validate_non_negative_index("theta", "d", d);
            validate_non_negative_index("theta", "q", q);
            num_params_r__ += ((d * d) * q);
            current_statement_begin__ = 18;
            validate_non_negative_index("SigCorr", "d", d);
            validate_non_negative_index("SigCorr", "d", d);
            num_params_r__ += ((d * (d - 1)) / 2);
            current_statement_begin__ = 19;
            validate_non_negative_index("sigma1", "d", d);
            num_params_r__ += d;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_varma() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 15;
        if (!(context__.contains_r("mu0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu0");
        pos__ = 0U;
        validate_non_negative_index("mu0", "d", d);
        context__.validate_dims("parameter initialization", "mu0", "row_vector_d", context__.to_vec(d));
        Eigen::Matrix<double, 1, Eigen::Dynamic> mu0(d);
        size_t mu0_j_1_max__ = d;
        for (size_t j_1__ = 0; j_1__ < mu0_j_1_max__; ++j_1__) {
            mu0(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.row_vector_unconstrain(mu0);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu0: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 16;
        if (!(context__.contains_r("phi")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable phi missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("phi");
        pos__ = 0U;
        validate_non_negative_index("phi", "d", d);
        validate_non_negative_index("phi", "d", d);
        validate_non_negative_index("phi", "p", p);
        context__.validate_dims("parameter initialization", "phi", "matrix_d", context__.to_vec(p,d,d));
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > phi(p, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(d, d));
        size_t phi_j_2_max__ = d;
        size_t phi_j_1_max__ = d;
        size_t phi_k_0_max__ = p;
        for (size_t j_2__ = 0; j_2__ < phi_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < phi_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < phi_k_0_max__; ++k_0__) {
                    phi[k_0__](j_1__, j_2__) = vals_r__[pos__++];
                }
            }
        }
        size_t phi_i_0_max__ = p;
        for (size_t i_0__ = 0; i_0__ < phi_i_0_max__; ++i_0__) {
            try {
                writer__.matrix_lub_unconstrain(-(1), 1, phi[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable phi: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 17;
        if (!(context__.contains_r("theta")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta");
        pos__ = 0U;
        validate_non_negative_index("theta", "d", d);
        validate_non_negative_index("theta", "d", d);
        validate_non_negative_index("theta", "q", q);
        context__.validate_dims("parameter initialization", "theta", "matrix_d", context__.to_vec(q,d,d));
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > theta(q, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(d, d));
        size_t theta_j_2_max__ = d;
        size_t theta_j_1_max__ = d;
        size_t theta_k_0_max__ = q;
        for (size_t j_2__ = 0; j_2__ < theta_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < theta_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < theta_k_0_max__; ++k_0__) {
                    theta[k_0__](j_1__, j_2__) = vals_r__[pos__++];
                }
            }
        }
        size_t theta_i_0_max__ = q;
        for (size_t i_0__ = 0; i_0__ < theta_i_0_max__; ++i_0__) {
            try {
                writer__.matrix_lub_unconstrain(-(1), 1, theta[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 18;
        if (!(context__.contains_r("SigCorr")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable SigCorr missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("SigCorr");
        pos__ = 0U;
        validate_non_negative_index("SigCorr", "d", d);
        validate_non_negative_index("SigCorr", "d", d);
        context__.validate_dims("parameter initialization", "SigCorr", "matrix_d", context__.to_vec(d,d));
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> SigCorr(d, d);
        size_t SigCorr_j_2_max__ = d;
        size_t SigCorr_j_1_max__ = d;
        for (size_t j_2__ = 0; j_2__ < SigCorr_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < SigCorr_j_1_max__; ++j_1__) {
                SigCorr(j_1__, j_2__) = vals_r__[pos__++];
            }
        }
        try {
            writer__.cholesky_factor_corr_unconstrain(SigCorr);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable SigCorr: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 19;
        if (!(context__.contains_r("sigma1")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma1 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma1");
        pos__ = 0U;
        validate_non_negative_index("sigma1", "d", d);
        context__.validate_dims("parameter initialization", "sigma1", "vector_d", context__.to_vec(d));
        Eigen::Matrix<double, Eigen::Dynamic, 1> sigma1(d);
        size_t sigma1_j_1_max__ = d;
        for (size_t j_1__ = 0; j_1__ < sigma1_j_1_max__; ++j_1__) {
            sigma1(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_lb_unconstrain(0, sigma1);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma1: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 15;
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> mu0;
            (void) mu0;  // dummy to suppress unused var warning
            if (jacobian__)
                mu0 = in__.row_vector_constrain(d, lp__);
            else
                mu0 = in__.row_vector_constrain(d);
            current_statement_begin__ = 16;
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> > phi;
            size_t phi_d_0_max__ = p;
            phi.reserve(phi_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < phi_d_0_max__; ++d_0__) {
                if (jacobian__)
                    phi.push_back(in__.matrix_lub_constrain(-(1), 1, d, d, lp__));
                else
                    phi.push_back(in__.matrix_lub_constrain(-(1), 1, d, d));
            }
            current_statement_begin__ = 17;
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> > theta;
            size_t theta_d_0_max__ = q;
            theta.reserve(theta_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < theta_d_0_max__; ++d_0__) {
                if (jacobian__)
                    theta.push_back(in__.matrix_lub_constrain(-(1), 1, d, d, lp__));
                else
                    theta.push_back(in__.matrix_lub_constrain(-(1), 1, d, d));
            }
            current_statement_begin__ = 18;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> SigCorr;
            (void) SigCorr;  // dummy to suppress unused var warning
            if (jacobian__)
                SigCorr = in__.cholesky_factor_corr_constrain(d, lp__);
            else
                SigCorr = in__.cholesky_factor_corr_constrain(d);
            current_statement_begin__ = 19;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> sigma1;
            (void) sigma1;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma1 = in__.vector_lb_constrain(0, d, lp__);
            else
                sigma1 = in__.vector_lb_constrain(0, d);
            // transformed parameters
            current_statement_begin__ = 26;
            validate_non_negative_index("mu", "n", n);
            validate_non_negative_index("mu", "d", d);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> mu(n, d);
            stan::math::initialize(mu, DUMMY_VAR__);
            stan::math::fill(mu, DUMMY_VAR__);
            current_statement_begin__ = 27;
            validate_non_negative_index("epsilon", "n", n);
            validate_non_negative_index("epsilon", "d", d);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> epsilon(n, d);
            stan::math::initialize(epsilon, DUMMY_VAR__);
            stan::math::fill(epsilon, DUMMY_VAR__);
            current_statement_begin__ = 28;
            validate_non_negative_index("sigma", "d", d);
            validate_non_negative_index("sigma", "d", d);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> sigma(d, d);
            stan::math::initialize(sigma, DUMMY_VAR__);
            stan::math::fill(sigma, DUMMY_VAR__);
            current_statement_begin__ = 29;
            validate_non_negative_index("sigma0", "d", d);
            validate_non_negative_index("sigma0", "d", d);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> sigma0(d, d);
            stan::math::initialize(sigma0, DUMMY_VAR__);
            stan::math::fill(sigma0, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 36;
            stan::math::assign(sigma, diag_pre_multiply(sigma1, SigCorr));
            current_statement_begin__ = 37;
            stan::math::assign(sigma0, multiply_lower_tri_self_transpose(sigma));
            current_statement_begin__ = 43;
            for (int i = 1; i <= n; ++i) {
                current_statement_begin__ = 45;
                stan::model::assign(mu, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            mu0, 
                            "assigning variable mu");
                current_statement_begin__ = 48;
                if (as_bool(logical_gt(p, 0))) {
                    current_statement_begin__ = 48;
                    for (int j = 1; j <= p; ++j) {
                        current_statement_begin__ = 48;
                        if (as_bool(logical_gt(i, j))) {
                            current_statement_begin__ = 48;
                            stan::model::assign(mu, 
                                        stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                        add(stan::model::rvalue(mu, stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), "mu"), multiply(get_base1(y, (i - j), "y", 1), get_base1(phi, j, "phi", 1))), 
                                        "assigning variable mu");
                        }
                    }
                }
                current_statement_begin__ = 51;
                if (as_bool(logical_gt(q, 0))) {
                    current_statement_begin__ = 51;
                    for (int j = 1; j <= q; ++j) {
                        current_statement_begin__ = 51;
                        if (as_bool(logical_gt(i, j))) {
                            current_statement_begin__ = 51;
                            stan::model::assign(mu, 
                                        stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                        add(stan::model::rvalue(mu, stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), "mu"), multiply(get_base1(epsilon, (i - j), "epsilon", 1), get_base1(theta, j, "theta", 1))), 
                                        "assigning variable mu");
                        }
                    }
                }
                current_statement_begin__ = 52;
                stan::model::assign(epsilon, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            subtract(get_base1(y, i, "y", 1), get_base1(mu, i, "mu", 1)), 
                            "assigning variable epsilon");
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 26;
            size_t mu_j_1_max__ = n;
            size_t mu_j_2_max__ = d;
            for (size_t j_1__ = 0; j_1__ < mu_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < mu_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(mu(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: mu" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable mu: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 27;
            size_t epsilon_j_1_max__ = n;
            size_t epsilon_j_2_max__ = d;
            for (size_t j_1__ = 0; j_1__ < epsilon_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < epsilon_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(epsilon(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: epsilon" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable epsilon: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 28;
            size_t sigma_j_1_max__ = d;
            size_t sigma_j_2_max__ = d;
            for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < sigma_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(sigma(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: sigma" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable sigma: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 29;
            size_t sigma0_j_1_max__ = d;
            size_t sigma0_j_2_max__ = d;
            for (size_t j_1__ = 0; j_1__ < sigma0_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < sigma0_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(sigma0(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: sigma0" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable sigma0: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            // model body
            current_statement_begin__ = 59;
            if (as_bool(logical_eq(get_base1(prior_mu0, 4, "prior_mu0", 1), 1))) {
                current_statement_begin__ = 59;
                lp_accum__.add(normal_log(mu0, get_base1(prior_mu0, 1, "prior_mu0", 1), get_base1(prior_mu0, 2, "prior_mu0", 1)));
            } else if (as_bool(logical_eq(get_base1(prior_mu0, 4, "prior_mu0", 1), 2))) {
                current_statement_begin__ = 60;
                lp_accum__.add(beta_log(mu0, get_base1(prior_mu0, 1, "prior_mu0", 1), get_base1(prior_mu0, 2, "prior_mu0", 1)));
            } else if (as_bool(logical_eq(get_base1(prior_mu0, 4, "prior_mu0", 1), 3))) {
                current_statement_begin__ = 61;
                lp_accum__.add(beta_log(mu0, get_base1(prior_mu0, 1, "prior_mu0", 1), get_base1(prior_mu0, 2, "prior_mu0", 1)));
            } else if (as_bool(logical_eq(get_base1(prior_mu0, 4, "prior_mu0", 1), 4))) {
                current_statement_begin__ = 62;
                lp_accum__.add(student_t_log(mu0, get_base1(prior_mu0, 3, "prior_mu0", 1), get_base1(prior_mu0, 1, "prior_mu0", 1), get_base1(prior_mu0, 2, "prior_mu0", 1)));
            } else if (as_bool(logical_eq(get_base1(prior_mu0, 4, "prior_mu0", 1), 5))) {
                current_statement_begin__ = 63;
                lp_accum__.add(cauchy_log(mu0, get_base1(prior_mu0, 1, "prior_mu0", 1), get_base1(prior_mu0, 2, "prior_mu0", 1)));
            } else if (as_bool(logical_eq(get_base1(prior_mu0, 4, "prior_mu0", 1), 9))) {
                current_statement_begin__ = 64;
                lp_accum__.add(gamma_log(mu0, get_base1(prior_mu0, 1, "prior_mu0", 1), get_base1(prior_mu0, 2, "prior_mu0", 1)));
            }
            current_statement_begin__ = 67;
            if (as_bool(logical_eq(get_base1(prior_sigma0, 4, "prior_sigma0", 1), 1))) {
                current_statement_begin__ = 67;
                lp_accum__.add(normal_log(sigma1, get_base1(prior_sigma0, 1, "prior_sigma0", 1), get_base1(prior_sigma0, 2, "prior_sigma0", 1)));
            } else if (as_bool(logical_eq(get_base1(prior_sigma0, 4, "prior_sigma0", 1), 4))) {
                current_statement_begin__ = 68;
                lp_accum__.add(student_t_log(sigma1, get_base1(prior_sigma0, 3, "prior_sigma0", 1), get_base1(prior_sigma0, 1, "prior_sigma0", 1), get_base1(prior_sigma0, 2, "prior_sigma0", 1)));
            } else if (as_bool(logical_eq(get_base1(prior_sigma0, 4, "prior_sigma0", 1), 5))) {
                current_statement_begin__ = 69;
                lp_accum__.add(cauchy_log(sigma1, get_base1(prior_sigma0, 1, "prior_sigma0", 1), get_base1(prior_sigma0, 2, "prior_sigma0", 1)));
            } else if (as_bool(logical_eq(get_base1(prior_sigma0, 4, "prior_sigma0", 1), 6))) {
                current_statement_begin__ = 70;
                lp_accum__.add(inv_gamma_log(sigma1, get_base1(prior_sigma0, 1, "prior_sigma0", 1), get_base1(prior_sigma0, 2, "prior_sigma0", 1)));
            } else if (as_bool(logical_eq(get_base1(prior_sigma0, 4, "prior_sigma0", 1), 7))) {
                current_statement_begin__ = 71;
                lp_accum__.add(inv_chi_square_log(sigma1, get_base1(prior_sigma0, 3, "prior_sigma0", 1)));
            }
            current_statement_begin__ = 74;
            lp_accum__.add(lkj_corr_cholesky_log(SigCorr, get_base1(prior_lkj, 1, "prior_lkj", 1)));
            current_statement_begin__ = 77;
            if (as_bool(logical_gt(p, 0))) {
                current_statement_begin__ = 78;
                for (int i = 1; i <= p; ++i) {
                    current_statement_begin__ = 79;
                    if (as_bool(logical_eq(get_base1(prior_ar, i, 4, "prior_ar", 1), 1))) {
                        current_statement_begin__ = 79;
                        lp_accum__.add(normal_log(to_vector(get_base1(phi, i, "phi", 1)), get_base1(prior_ar, i, 1, "prior_ar", 1), get_base1(prior_ar, i, 2, "prior_ar", 1)));
                    } else {
                        current_statement_begin__ = 80;
                        lp_accum__.add(normal_log(to_vector(get_base1(phi, i, "phi", 1)), 0, 1));
                    }
                }
            }
            current_statement_begin__ = 84;
            if (as_bool(logical_gt(q, 0))) {
                current_statement_begin__ = 85;
                for (int i = 1; i <= q; ++i) {
                    current_statement_begin__ = 86;
                    if (as_bool(logical_eq(get_base1(prior_ma, i, 4, "prior_ma", 1), 1))) {
                        current_statement_begin__ = 86;
                        lp_accum__.add(normal_log(to_vector(get_base1(theta, i, "theta", 1)), get_base1(prior_ma, i, 1, "prior_ma", 1), get_base1(prior_ma, i, 2, "prior_ma", 1)));
                    } else {
                        current_statement_begin__ = 87;
                        lp_accum__.add(normal_log(to_vector(get_base1(theta, i, "theta", 1)), 0, 1));
                    }
                }
            }
            current_statement_begin__ = 91;
            for (int i = 1; i <= n; ++i) {
                current_statement_begin__ = 91;
                lp_accum__.add(multi_normal_cholesky_log(get_base1(epsilon, i, "epsilon", 1), rep_vector(0, d), sigma));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("mu0");
        names__.push_back("phi");
        names__.push_back("theta");
        names__.push_back("SigCorr");
        names__.push_back("sigma1");
        names__.push_back("mu");
        names__.push_back("epsilon");
        names__.push_back("sigma");
        names__.push_back("sigma0");
        names__.push_back("loglik");
        names__.push_back("log_lik");
        names__.push_back("fit");
        names__.push_back("residual");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(d);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(p);
        dims__.push_back(d);
        dims__.push_back(d);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(q);
        dims__.push_back(d);
        dims__.push_back(d);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(d);
        dims__.push_back(d);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(d);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dims__.push_back(d);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dims__.push_back(d);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(d);
        dims__.push_back(d);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(d);
        dims__.push_back(d);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dims__.push_back(d);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dims__.push_back(d);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_varma_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, 1, Eigen::Dynamic> mu0 = in__.row_vector_constrain(d);
        size_t mu0_j_1_max__ = d;
        for (size_t j_1__ = 0; j_1__ < mu0_j_1_max__; ++j_1__) {
            vars__.push_back(mu0(j_1__));
        }
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > phi;
        size_t phi_d_0_max__ = p;
        phi.reserve(phi_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < phi_d_0_max__; ++d_0__) {
            phi.push_back(in__.matrix_lub_constrain(-(1), 1, d, d));
        }
        size_t phi_j_2_max__ = d;
        size_t phi_j_1_max__ = d;
        size_t phi_k_0_max__ = p;
        for (size_t j_2__ = 0; j_2__ < phi_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < phi_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < phi_k_0_max__; ++k_0__) {
                    vars__.push_back(phi[k_0__](j_1__, j_2__));
                }
            }
        }
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > theta;
        size_t theta_d_0_max__ = q;
        theta.reserve(theta_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < theta_d_0_max__; ++d_0__) {
            theta.push_back(in__.matrix_lub_constrain(-(1), 1, d, d));
        }
        size_t theta_j_2_max__ = d;
        size_t theta_j_1_max__ = d;
        size_t theta_k_0_max__ = q;
        for (size_t j_2__ = 0; j_2__ < theta_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < theta_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < theta_k_0_max__; ++k_0__) {
                    vars__.push_back(theta[k_0__](j_1__, j_2__));
                }
            }
        }
        Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> SigCorr = in__.cholesky_factor_corr_constrain(d);
        size_t SigCorr_j_2_max__ = d;
        size_t SigCorr_j_1_max__ = d;
        for (size_t j_2__ = 0; j_2__ < SigCorr_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < SigCorr_j_1_max__; ++j_1__) {
                vars__.push_back(SigCorr(j_1__, j_2__));
            }
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> sigma1 = in__.vector_lb_constrain(0, d);
        size_t sigma1_j_1_max__ = d;
        for (size_t j_1__ = 0; j_1__ < sigma1_j_1_max__; ++j_1__) {
            vars__.push_back(sigma1(j_1__));
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 26;
            validate_non_negative_index("mu", "n", n);
            validate_non_negative_index("mu", "d", d);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> mu(n, d);
            stan::math::initialize(mu, DUMMY_VAR__);
            stan::math::fill(mu, DUMMY_VAR__);
            current_statement_begin__ = 27;
            validate_non_negative_index("epsilon", "n", n);
            validate_non_negative_index("epsilon", "d", d);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> epsilon(n, d);
            stan::math::initialize(epsilon, DUMMY_VAR__);
            stan::math::fill(epsilon, DUMMY_VAR__);
            current_statement_begin__ = 28;
            validate_non_negative_index("sigma", "d", d);
            validate_non_negative_index("sigma", "d", d);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> sigma(d, d);
            stan::math::initialize(sigma, DUMMY_VAR__);
            stan::math::fill(sigma, DUMMY_VAR__);
            current_statement_begin__ = 29;
            validate_non_negative_index("sigma0", "d", d);
            validate_non_negative_index("sigma0", "d", d);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> sigma0(d, d);
            stan::math::initialize(sigma0, DUMMY_VAR__);
            stan::math::fill(sigma0, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 36;
            stan::math::assign(sigma, diag_pre_multiply(sigma1, SigCorr));
            current_statement_begin__ = 37;
            stan::math::assign(sigma0, multiply_lower_tri_self_transpose(sigma));
            current_statement_begin__ = 43;
            for (int i = 1; i <= n; ++i) {
                current_statement_begin__ = 45;
                stan::model::assign(mu, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            mu0, 
                            "assigning variable mu");
                current_statement_begin__ = 48;
                if (as_bool(logical_gt(p, 0))) {
                    current_statement_begin__ = 48;
                    for (int j = 1; j <= p; ++j) {
                        current_statement_begin__ = 48;
                        if (as_bool(logical_gt(i, j))) {
                            current_statement_begin__ = 48;
                            stan::model::assign(mu, 
                                        stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                        add(stan::model::rvalue(mu, stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), "mu"), multiply(get_base1(y, (i - j), "y", 1), get_base1(phi, j, "phi", 1))), 
                                        "assigning variable mu");
                        }
                    }
                }
                current_statement_begin__ = 51;
                if (as_bool(logical_gt(q, 0))) {
                    current_statement_begin__ = 51;
                    for (int j = 1; j <= q; ++j) {
                        current_statement_begin__ = 51;
                        if (as_bool(logical_gt(i, j))) {
                            current_statement_begin__ = 51;
                            stan::model::assign(mu, 
                                        stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                        add(stan::model::rvalue(mu, stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), "mu"), multiply(get_base1(epsilon, (i - j), "epsilon", 1), get_base1(theta, j, "theta", 1))), 
                                        "assigning variable mu");
                        }
                    }
                }
                current_statement_begin__ = 52;
                stan::model::assign(epsilon, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            subtract(get_base1(y, i, "y", 1), get_base1(mu, i, "mu", 1)), 
                            "assigning variable epsilon");
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t mu_j_2_max__ = d;
                size_t mu_j_1_max__ = n;
                for (size_t j_2__ = 0; j_2__ < mu_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < mu_j_1_max__; ++j_1__) {
                        vars__.push_back(mu(j_1__, j_2__));
                    }
                }
                size_t epsilon_j_2_max__ = d;
                size_t epsilon_j_1_max__ = n;
                for (size_t j_2__ = 0; j_2__ < epsilon_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < epsilon_j_1_max__; ++j_1__) {
                        vars__.push_back(epsilon(j_1__, j_2__));
                    }
                }
                size_t sigma_j_2_max__ = d;
                size_t sigma_j_1_max__ = d;
                for (size_t j_2__ = 0; j_2__ < sigma_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
                        vars__.push_back(sigma(j_1__, j_2__));
                    }
                }
                size_t sigma0_j_2_max__ = d;
                size_t sigma0_j_1_max__ = d;
                for (size_t j_2__ = 0; j_2__ < sigma0_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < sigma0_j_1_max__; ++j_1__) {
                        vars__.push_back(sigma0(j_1__, j_2__));
                    }
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 94;
            double loglik;
            (void) loglik;  // dummy to suppress unused var warning
            stan::math::initialize(loglik, DUMMY_VAR__);
            stan::math::fill(loglik, DUMMY_VAR__);
            stan::math::assign(loglik,0);
            current_statement_begin__ = 95;
            validate_non_negative_index("log_lik", "n", n);
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik(n);
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);
            current_statement_begin__ = 96;
            validate_non_negative_index("fit", "n", n);
            validate_non_negative_index("fit", "d", d);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> fit(n, d);
            stan::math::initialize(fit, DUMMY_VAR__);
            stan::math::fill(fit, DUMMY_VAR__);
            current_statement_begin__ = 97;
            validate_non_negative_index("residual", "n", n);
            validate_non_negative_index("residual", "d", d);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> residual(n, d);
            stan::math::initialize(residual, DUMMY_VAR__);
            stan::math::fill(residual, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 99;
            for (int i = 1; i <= n; ++i) {
                current_statement_begin__ = 100;
                stan::model::assign(residual, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            transpose(multi_normal_cholesky_rng(get_base1(epsilon, i, "epsilon", 1), sigma, base_rng__)), 
                            "assigning variable residual");
                current_statement_begin__ = 101;
                stan::model::assign(fit, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            subtract(get_base1(y, i, "y", 1), get_base1(residual, i, "residual", 1)), 
                            "assigning variable fit");
                current_statement_begin__ = 102;
                stan::model::assign(log_lik, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            multi_normal_cholesky_log(get_base1(y, i, "y", 1), get_base1(mu, i, "mu", 1), sigma), 
                            "assigning variable log_lik");
                current_statement_begin__ = 103;
                stan::math::assign(loglik, (loglik + get_base1(log_lik, i, "log_lik", 1)));
            }
            // validate, write generated quantities
            current_statement_begin__ = 94;
            vars__.push_back(loglik);
            current_statement_begin__ = 95;
            size_t log_lik_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik(j_1__));
            }
            current_statement_begin__ = 96;
            size_t fit_j_2_max__ = d;
            size_t fit_j_1_max__ = n;
            for (size_t j_2__ = 0; j_2__ < fit_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < fit_j_1_max__; ++j_1__) {
                    vars__.push_back(fit(j_1__, j_2__));
                }
            }
            current_statement_begin__ = 97;
            size_t residual_j_2_max__ = d;
            size_t residual_j_1_max__ = n;
            for (size_t j_2__ = 0; j_2__ < residual_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < residual_j_1_max__; ++j_1__) {
                    vars__.push_back(residual(j_1__, j_2__));
                }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_varma";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t mu0_j_1_max__ = d;
        for (size_t j_1__ = 0; j_1__ < mu0_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "mu0" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t phi_j_2_max__ = d;
        size_t phi_j_1_max__ = d;
        size_t phi_k_0_max__ = p;
        for (size_t j_2__ = 0; j_2__ < phi_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < phi_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < phi_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "phi" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t theta_j_2_max__ = d;
        size_t theta_j_1_max__ = d;
        size_t theta_k_0_max__ = q;
        for (size_t j_2__ = 0; j_2__ < theta_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < theta_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < theta_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "theta" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t SigCorr_j_2_max__ = d;
        size_t SigCorr_j_1_max__ = d;
        for (size_t j_2__ = 0; j_2__ < SigCorr_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < SigCorr_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "SigCorr" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t sigma1_j_1_max__ = d;
        for (size_t j_1__ = 0; j_1__ < sigma1_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma1" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t mu_j_2_max__ = d;
            size_t mu_j_1_max__ = n;
            for (size_t j_2__ = 0; j_2__ < mu_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < mu_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "mu" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t epsilon_j_2_max__ = d;
            size_t epsilon_j_1_max__ = n;
            for (size_t j_2__ = 0; j_2__ < epsilon_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < epsilon_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "epsilon" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t sigma_j_2_max__ = d;
            size_t sigma_j_1_max__ = d;
            for (size_t j_2__ = 0; j_2__ < sigma_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "sigma" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t sigma0_j_2_max__ = d;
            size_t sigma0_j_1_max__ = d;
            for (size_t j_2__ = 0; j_2__ < sigma0_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < sigma0_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "sigma0" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        if (!include_gqs__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "loglik";
        param_names__.push_back(param_name_stream__.str());
        size_t log_lik_j_1_max__ = n;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t fit_j_2_max__ = d;
        size_t fit_j_1_max__ = n;
        for (size_t j_2__ = 0; j_2__ < fit_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < fit_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "fit" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t residual_j_2_max__ = d;
        size_t residual_j_1_max__ = n;
        for (size_t j_2__ = 0; j_2__ < residual_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < residual_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "residual" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t mu0_j_1_max__ = d;
        for (size_t j_1__ = 0; j_1__ < mu0_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "mu0" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t phi_j_2_max__ = d;
        size_t phi_j_1_max__ = d;
        size_t phi_k_0_max__ = p;
        for (size_t j_2__ = 0; j_2__ < phi_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < phi_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < phi_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "phi" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t theta_j_2_max__ = d;
        size_t theta_j_1_max__ = d;
        size_t theta_k_0_max__ = q;
        for (size_t j_2__ = 0; j_2__ < theta_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < theta_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < theta_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "theta" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t SigCorr_j_1_max__ = ((d * (d - 1)) / 2);
        for (size_t j_1__ = 0; j_1__ < SigCorr_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "SigCorr" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t sigma1_j_1_max__ = d;
        for (size_t j_1__ = 0; j_1__ < sigma1_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma1" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t mu_j_2_max__ = d;
            size_t mu_j_1_max__ = n;
            for (size_t j_2__ = 0; j_2__ < mu_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < mu_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "mu" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t epsilon_j_2_max__ = d;
            size_t epsilon_j_1_max__ = n;
            for (size_t j_2__ = 0; j_2__ < epsilon_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < epsilon_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "epsilon" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t sigma_j_2_max__ = d;
            size_t sigma_j_1_max__ = d;
            for (size_t j_2__ = 0; j_2__ < sigma_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < sigma_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "sigma" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t sigma0_j_2_max__ = d;
            size_t sigma0_j_1_max__ = d;
            for (size_t j_2__ = 0; j_2__ < sigma0_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < sigma0_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "sigma0" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        if (!include_gqs__) return;
        param_name_stream__.str(std::string());
        param_name_stream__ << "loglik";
        param_names__.push_back(param_name_stream__.str());
        size_t log_lik_j_1_max__ = n;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t fit_j_2_max__ = d;
        size_t fit_j_1_max__ = n;
        for (size_t j_2__ = 0; j_2__ < fit_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < fit_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "fit" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t residual_j_2_max__ = d;
        size_t residual_j_1_max__ = n;
        for (size_t j_2__ = 0; j_2__ < residual_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < residual_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "residual" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }
}; // model
}  // namespace
typedef model_varma_namespace::model_varma stan_model;
#endif
